config/routes.rb
Rails.application.routes.draw do

  
  resources :service_reminders

  resources :services

  resources :fuels

  resources :vehicles
  post 'pusher/auth'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invoices
  resources :supports
  resources :items do
    collection do
      get "inventory_head" 
      post "inventory_update"
    end
  end
  resources :parts
  namespace :api do
    namespace :v1 do
      post "/sign_in", :to => 'sessions#create'
      delete "/sign_out", :to => 'sessions#destroy'
      post "/sign_up", :to => 'registrations#create'
      post "/users/password", :to => 'passwords#create'
      get "/dashboards/username",:to =>'dashboards#username'
      get "/conversations/chat_user",:to =>'conversations#chat_user'
      post "/conversations/conversation_user",:to =>'conversations#conversation_user'
      post "/conversations/create",:to =>'conversations#create'
      get "/conversations/show_message",:to =>'conversations#show_message'
      get "/dashboards/weather",:to =>'dashboards#weather'
      get "/chemical_add",:to =>'chemicals#chemical_add'
      post "/chemical_used",:to =>'chemicals#chemical_used'
      get "/chemical_display",:to=>"chemicals#chemical_display"
      post "/chemical_test" , :to=>"chemicals#chemical_test"
      get "/view_chemical_result" , :to=>"chemicals#view_chemical_result"
      get "/chemical_test_range", :to=>"chemicals#chemical_test_range"
      get "/service_item", :to=>"chemicals#service_item"
      post "/service_item_create" ,:to=>"chemicals#service_item_create"
      get "/service_item_display", :to=>"chemicals#service_item_display"

      post "/charge_create",:to=>"charges#charge_create"
      post "/update_coordinates",:to=>"trackings#update_coordinates"
      get "/show_points",:to=>"trackings#show_points"
      get "/deactive_points",:to=>"trackings#deactive_points"
      resources :clients do
        member do
          get "client_property" 
          post "update_client"
        end
      end
      resources :jobs do
        collection do
          get "today_schedule"
          get 'signature_job'
        end
        member do
          get "job_invoice"
          post "update_job"
          post "close_job"
          post "job_payment"
          post "reopen_job"
        end
      end
      resources :properties do
        member do
          post "update_property"
        end
      end
      resources :items do
        member do
          post "update_item"
        end
      end
      resources :quotes do
        member do
          post "update_quote"
          get "find_quote"
          post "signature_quote"
          post "quotes_image"
          post "quote_image_save"
        end
      end
      resources :invoices do
        member do
        post "update_invoice" 
        end
      end
      resources :basic_tasks do 
        collection do
          get "today_task"
        end
        member do
          post "update_task"
        end

      end

      resources :timesheets do
        member do
        post "update_timesheet" 
        end
      end

      resources :home do
        collection do
          get "weather"
        end
      end

      resources :expenses do 
        member do   
         post "update_expense"  
        end
      end
    end
  end

  resources :numbers do
    collection do
      post :update_ivr_number
      post :search
    end
  end
  resources :key_actions

  resources :keys

  resources :ivrs do

    collection do
      post 'create_beta'
      post 'add_sub_menu'
      post 'create_feedback'
      post 'check_email'
      post 'key_description'
    end
    member do
      get 'twiml/repeat_menu(/:sub_menu_id)', :to => "ivrs#twiml_repeat_menu" , :as => :twiml_repeat
      get 'twiml(/:sub_menu_id)' , :to => "ivrs#twiml" , :as => :twiml
      get 'handle_recording'
      get 'calls'
      get 'release'
      get 'templates'
      get 'apply_template'
      post 'sms_callback'
      get 'analytics'
      post 'filters'
    end
  end

  get "action_types" => 'action_types#index'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash

    end
    collection do
      get :notify
      get :update_notify
      get :display_notify
    end

  end
  resources :classifieds do
    member do
      get :media
      patch :media_save
      post :media_save
    end 
  end

  resources :subscriptions do 
    collection do
      get :plan
      post :change_plan
      post :downgrade_plan
    end
  end
  resources :maps do
    collection do
      get :zoom
      get :optimize 
      get :assigned_team
      get :change_assign
      post :reassign
      get :map_show
      post :property_estimate
      get :lead
      get :add_marker
      post :display_address
      get :create_lead
      post :add_lead
    end
  end 
  resources :quotes
  resources :notifications 

  resources :events do
    collection do
      get :to_dos
      post :move
      post "visit_complete_event/:visit_id" => "events#visit_complete_event", as: "visit_complete_event" 
      get "visit_view_detail_event/:visit_id" => "events#visit_view_detail_event", as: "visit_view_detail_event"
      get "edit_visit_event/:visit_id" => "events#edit_visit_event", as: "edit_visit_event"
      post "update_visit_event/:visit_id" =>  "events#update_visit_event", as: "update_visit_event"
      get "destroy_visit_event/:job_id/:visit_id" =>  "events#destroy_visit_event", as: "destroy_visit_event"
      get 'new_job_event' => 'events#new_job_event', as: 'new_job_event'
      post 'search_job_client' => 'events#search_job_client', as: 'search_job_client'
    end
    get :view_detail
  end

  resources :basic_tasks do
    collection do
      get :to_dos 
      post :move
    end
    post :complete_basic_task
    get :view_detail
  end

  resources :jobs do 
    collection do 
      get "recurring_job"
    end
  end
  resources :properties do
    member do
      get :manually_geocode
      post "update_property"
    end
    collection do
      post :location_update
      post :property_service_plan
      post :pool_update_active
      get :convert_client
      post :converted
      get :lead_message
      post :lead_message_pdf
      post :property_tag
      post :tag_delete
      post :templates_display
      get :email_message
      post :message_email_sent
      get :lead_mailer
    end
  end

  resources :spa_pooles do 
    collection do
      get :property_pool_data
      post :pool_data_create
      post :pool_data_update
      get :pool_data_edit
      get :spa_data
      post :spa_data_create
      get :spa_data_edit
      post :spa_data_update
      post :calculate_gallonage
      post :calculate_spa_volume
      post :pool_shape_change
      post :spa_shape_change
    end
  end

  get "/dashboard" =>"dashboards#dashboard"
  get "/get_summary_data" =>"dashboards#get_summary_data"
  get "/get_quick_links"  =>"dashboards#get_quick_links"
  get "/weather_data"  =>"dashboards#weather_data"

  resources :clients do
    collection do
      get :demo_deactive 
      get :new_client
    end
    member do
      post :payment
    end
  end

  resources :documents do
    collection do
      get :document_box
      get :document_setting
      post :document_check
    end
    member do
      get :download
      get :delete_account # admin delete its account
    end
  end

  resources :intuits do
    collection do
      get :authenticate
      get :oauth_callback
      get :closed_qb_account
    end
  end

  resources :email_notifications do
    collection do
      get 'reply_message' 
      post 'message_create' 
      get 'thanks_message'
      post 'email_read'
      get 'chat_popup'
    end
  end

  resources :timesheets do 
    collection do
      get 'prev_day'
      get 'next_day'
      get 'category_new'
      get 'payroll'
      get 'prev_payroll'
      get 'next_payroll'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end
  end
  resources :expenses do
    collection do
      get 'mile_category' , :as => "expenses/mileage"
      post 'create_mileage'
      post 'category_create'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end

  end
  resources :pool_services do 
    collection do 
      get "pool_service"
      get "spa_service"
      post "service_create"
      get "chemical_items"
      post "chemical_items_create" 
      get "pool_chemical_test"
      post "check_pool_test"
      get "chemical_used"
      post "chemical_used_create"
      get "service_items"
      post "service_items_create"
      get "market_source"
      post "source_create"
      post "source_update"
      get "service_plan"
      post "service_plan_create"
      post "service_plan_update"
      get :service_plan_label
      post :update_plan_label
    end
    member do
      get "source_edit"
      get "source_delete"
      get "service_plan_edit"
      get "service_plan_delete"
    end
  end
  resources :chamicals
  resources :postcards, only: [:index, :create] 
  devise_for :users, :controllers => {:sessions=>"sessions",:confirmations=>"confirmations",:registrations => "registrations",:passwords=>"passwords",:omniauth_callbacks => "omniauth_callbacks"}
  

  post '/twilio_call' =>"communications#twilio_call"
  post '/twilio_connect' =>"communications#twilio_connect"
  post '/property_note' =>"communications#property_note"
  post '/property_email' =>"communications#property_email"
  post '/property_sms'   =>"communications#property_sms"
  get '/more_activity'   =>"communications#more_activity"
  get '/edit_note_activity' =>"communications#edit_note_activity"
  post '/update_note_activty' =>"communications#update_note_activty"
  get '/filter_activity' =>"communications#filter_activity"

app/views/home/_client_payment.html.erb
<div class="modal fade" id="paymentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Payment</h4>
      </div>
      <div class="modal-body">
        <div id="client_selector">
          <p>Which Customer would you like to use for this Invoice?</p> 
          <br/>

          <div class ="search-div row">
            <%= text_field_tag :search, nil, :class=>"form-control search_input",:placeholder=>"Search Clients...",:require=>true,:id=>"search_input_job_client_model",:style=>"width: 48%;",:onkeyup => "searchClientInvoiceModel($(this).val())" %>
            <span class="or">or</span>
          
          <%= link_to 'Create New Customer', new_client_path(:id=>"invoice"),:class=>"button_new_create",:style=>"float:right;"%><br/><br/>
          </div>
          <h4>Some Recently Used Clients:</h4><br/>

          <ul class="thicklist invoice_client "id="client_list_display"> 
            <%if !@clients.blank?%>
              <% @clients.each do |client| %>
                <li>
                  <div class="popover_user">
                    <i class="fa fa-user fa-2"></i>
                  </div>
                  <div class="user_contain_search">
                    <%= link_to client_payment_path(client), remote: true, class: "row spin_on_click", data: {toggle: "modal", target: '#payment_show'} do %>   
                      <h3 class="client_name individual">
                        <%= client.initial rescue "" %>
                        <%= client.first_name.titleize rescue "" %>
                        <%= client.last_name.titleize rescue "" %>&nbsp;(<%=client.company_name.titleize rescue "" %>)
                      </h3>
                      <span class="last_active" style="float:right;">
                        Activity &nbsp;<%= time_ago_in_words(client.created_at, include_seconds: true) rescue "" %>&nbsp; ago
                      </span>
                      <span style="display:inline-block; width:120px; padding-left:25px;"><%= client.properties.count rescue "" %> Pool</span>
                      <span><%= client.phone_number rescue "" %></span>
                    <% end %>
                  </div>
                </li>
              <% end %>
            <% else %>
              No result found
            <%end%>
          </ul>
        </div>  
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
<script>
  paymentClient();
</script>

app/views/home/_get_emails_communication_summary.html.erb
<div class="tables" style="margin-top:4px!important;">
  <table class="sortable wide" cellspacing="0" cellpadding="0" id="report_jobs">
    <thead class="thead">
      <tr>
        <th width="145px" class="client_name">Customer Name</th>
        <th width="189px" class="sent_date">Sent date</th>
        <th width="257px" class="to">To</th>
        <th width="169px" class="cc">CC</th>
        <th width="169px" class="subject">Subjet</th>
        <th width="169px" class="status1">status</th>
        <th width="225px" class="type">Type</th>
        <th width="92px" class="sent_time">~Sent Time</th>
        <th width="92px" class="opened_date">Opened Date</th>
        <th width="42px" class="open">Open</th>
      </tr>
    </thead>
    <% unless @emails_communication_summary.blank?%>
      <% @emails_communication_summary.each_with_index do |emails,i| %>
        <tr> 
          <td class="client_name"><%= current_user.clients.find(emails.client_id).first_name rescue "" %> <%= current_user.clients.find(emails.client_id).last_name rescue "" %></td>
          <td class="sent_date"><%= emails.sent_date.strftime("%m-%d-%Y") rescue "" %></td>
          <td class="to">
            <% emails.to.each_with_index do |to, i| %>
              <% if i==0 %>
                <%= to %>
              <% else %>
                , <%= to %>
              <% end %>
            <% end %>
          </td>
          <td class="cc"><%= cc rescue "" %></td>
          <td class="subject"><%= emails.subject rescue "" %></td>
          <td class="status1"><%= emails.status rescue "" %></td>
          <td class="type"><%= emails.type rescue "" %></td>
          <td class="sent_time"><%= emails.sent_time.strftime("%H:%M %b") rescue "" %></td>
          <td class="opened_date"><%= emails.opened_date rescue ""%></td>
          <td class="open"><a target="_blank" href="#" class="open ui-icon ui-icon-newwin">open</a></td>
        </tr>
      <% end %>
    <%end%> 
  </table>
</div>
<script type="text/javascript">
  table_sort_function()
  table_column_select()
</script>

app/views/home/_job_client_search.html.erb
<div class="modal fade" id="job_model_open" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;" data-backdrop="static" data-keyboard="false" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header new-modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Work Order</h4>
      </div>
      <div class="modal-body">
        <div id="client_selector">
         <p> Which Customer would you like to use for this Work Order? </p>
          <%= text_field_tag :search, nil, :class=>"form-control search_input",:placeholder=>"Search Clients...",:require=>true,:id=>"search_input_job_client_model",:style=>"width: 48%;",:onkeyup => "searchClientJobModel($(this).val())" %>
            <span class="or">or</span>
          
           <%= link_to 'Create New Customer', new_client_path(:id=>"job"),:class=>"button_new_create save-new-btn1" ,:style=>"float:right;"%><br/><br/>
           </div>
          <h4>Some Recently Used Customers:</h4>
          <br/>
          <ul class="thicklist"  id="client_list_display"> 
            <%= render "jobs/search_client_job"%>
          </ul>
        </div>
      </div>
      <!-- <div class="modal-footer">
      </div> -->
    </div>
  </div>
</div>

app/views/home/_managment_column_client_popup.html.erb
<%unless params[:display_method].blank?%>
	<div id="column_selector_model" class=" modal fade column_selector_model click_focus" tabindex="-1" role="tool-tip" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
		<label>
			<input type="checkbox" checked="checked" name="name"> Name
		</label>
		<label>
			<input type="checkbox" checked="checked" name="street1"> Street1
		</label>
		<label>
			<input type="checkbox" checked="checked" name="street2"> Street2
		</label>
		<label>
			<input type="checkbox" checked="checked" name="city"> City
		</label>
		<label>
			<input type="checkbox" checked="checked" name="state"> State
		</label>
		<label>
			<input type="checkbox" checked="checked" name="country"> Country
		</label>
		<label>
			<input type="checkbox" checked="checked" name="zip_code"> Zip Code
		</label>
		<label>
			<input type="checkbox" checked="checked" name="open"> Open
		</label>
	</div>
<% else %>
	<div id="column_selector_model" class=" modal fade click_focus" tabindex="-1" role="tool-tip" aria-labelledby="myModalLabel" aria-hidden="true">
		<label>
			<input type="checkbox" checked="checked" name="contact"> Contact
		</label>
		<label>
			<input type="checkbox" checked="checked" name="company"> Company
		</label>
		<label>
			<input type="checkbox" checked="checked" name="phone"> Phone
		</label>
		<label>
			<input type="checkbox" checked="checked" name="e-mail"> E-mail
		</label>
		<label>
			<input type="checkbox" checked="checked" name="billing-address"> Billing Address
		</label>
		<label>
			<input type="checkbox" checked="checked" name="created-date"> Created Date
		</label>
		<label>
			<input type="checkbox" checked="checked" name="open"> Open
		</label>
	</div>
<% end %>

app/views/home/_product_and_service_popup.html.erb
<div id="column_selector_model" class=" modal fade column_selector_model click_focus" tabindex="-1" role="tool-tip" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<label>
		<input type="checkbox" checked="checked" name="name"> Name
	</label>
	<label>
		<input type="checkbox" checked="checked" name="quote_qty"> Estimate Qty
	</label>
	<label>
		<input type="checkbox" checked="checked" name="quot_doller"> Estimate $
	</label>
	<label>
		<input type="checkbox" checked="checked" name="on_job_qty"> On Work Orders Qty
	</label>
	<label>
		<input type="checkbox" checked="checked" name="on_job_doller"> On Work Orders $
	</label>
	<label>
		<input type="checkbox" checked="checked" name="invoice_qty"> Invoiced Qty
	</label>
	<label>
		<input type="checkbox" checked="checked" name="invoiced_doller"> Invoiced $
	</label>
</div>

app/views/home/_projected_income_summary.html.erb
<div id="summary" style="margin:10px;">
  <div data-dynamic="true" class="summary_bars">
    <%= link_to("/reports/projected_income", :class=>"subsection_link #{get_selected_default}" ) do %>
      <h3>
        Outstanding
        <span class="count"><%= @due_total_invoice.count %></span>
      </h3>
       <span data-value="<%= get_due_invoice_total("more_than_30", @due_total_invoice) %>" class="total" style="width: 330px;">$<%= get_due_invoice_total("", @due_total_invoice) %></span>
    <% end %>
    <div class="short_separator"></div><br><br><br><h4>Due In</h4>
    <%= link_to("/reports/projected_income/7_days", :class=>"subsection_link #{get_selected("7_days")}" ) do %>
      <h3>
        < 7 days
        <span class="count"><%= get_due_invoice_count("7_days", @due_total_invoice) %></span>
      </h3>
       <span data-value="<%= get_due_invoice_total("more_than_30", @due_total_invoice) %>" class="total" style="width: 330px;">$<%= get_due_invoice_total("7_days", @due_total_invoice) %></span>
    <% end %>
    <%= link_to("/reports/projected_income/30_days", :class=>"subsection_link #{get_selected("30_days")}" ) do %>
      <h3>
        7 - 30 days
        <span class="count"><%= get_due_invoice_count("30_days", @due_total_invoice) %></span>
      </h3>
       <span data-value="<%= get_due_invoice_total("more_than_30", @due_total_invoice) %>" class="total" style="width: 330px;">$<%= get_due_invoice_total("30_days", @due_total_invoice) %></span>
    <% end %>
    <%= link_to("/reports/projected_income/more_than_30", :class=>"subsection_link #{get_selected("more_than_30")}" ) do %>
      <h3>
        > 30 days
        <span class="count"><%= get_due_invoice_count("more_than_30", @due_total_invoice) %></span>
      </h3>
       <span data-value="<%= get_due_invoice_total("more_than_30", @due_total_invoice) %>" class="total" style="width: 330px;">$<%= get_due_invoice_total("more_than_30", @due_total_invoice) %></span>
    <% end %>
    <div class="short_separator"></div>
    <%= link_to("/reports/projected_income/late", :class=>"subsection_link #{get_selected("late")}" ) do %>
      <h3>
        Late
        <span class="count"><%= get_due_invoice_count("late", @due_total_invoice) %></span>
      </h3>
       <span data-value="<%= get_due_invoice_total("more_than_30", @due_total_invoice) %>" class="total" style="width: 330px;">$<%= get_due_invoice_total("late", @due_total_invoice) %></span>
    <% end %>
  </div>
</div>

app/views/home/_service_edit.html.erb
<!-- Modal -->
<div class="modal fade" id="product_service_<%=service_name.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
	<% if service %>
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header new-modal-header">
	        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Edit <%= service_name.name rescue '' %></h4>
	      </div>
	      <div class="modal-body">
	      	<div class="content">
					  <%= form_tag update_service_path(service_name) ,:class=>"compressed_form work_item" do%>

					    <p>
					      <label for="work_item_name" class="large">Name</label>
					      <%= text_field_tag "work_item[name]",nil,:value=>service_name.name,:class=>"large name", :id=>"work_item_name"%>
					    </p>

					    <p>
					      <label for="work_item_description">Description</label>
					      <%= text_area_tag "work_item[description]",service_name.description,:cols=>"50",:id=>"work_item_description" %>
					    </p>

					    <p>
					    	<label for="work_item_default_unit_cost">Default Unit Cost $</label>
					      <%= text_field_tag "work_item[unit_cost]",nil,:value=>service_name.unit_cost,:class=>"large name", :placeholder=>"0.00", :id=>"work_item_default_unit_cost"%>
					    </p>

					    <p>
					    	<% if service_name.non_taxable %>
						      <input type="hidden" value="0" name="work_item[non_taxable]"><input type="checkbox" value="1" name="work_item[non_taxable]" id="work_item_nontaxable" checked="checked">
						      <label for="work_item_nontaxable">Non-taxable?</label>
						      <span class="description">Should this item be exempt from tax?</span>
						    <%else%>
						   	 	<input type="hidden" value="0" name="work_item[non_taxable]"><input type="checkbox" value="1" name="work_item[non_taxable]" id="work_item_nontaxable">
						      <label for="work_item_nontaxable">Non-taxable?</label>
						      <span class="description">Should this item be exempt from tax?</span>
						    <%end%>  
					    </p>

					    <p>
					    	<% if service_name.active %>
						      <input type="hidden" value="0" name="work_item[active]"><input type="checkbox" value="1" name="work_item[active]" id="work_item_visible" checked="checked">
						      <label for="work_item_visible">Active?</label>
						      <span class="description">Should this be an option for Estimate, Work Orders &amp; Invoices?</span>
						    <%else%>
						    	<input type="hidden" value="0" name="work_item[active]"><input type="checkbox" value="1" name="work_item[active]" id="work_item_visible">
						      <label for="work_item_visible">Active?</label>
						      <span class="description">Should this be an option for Estimate, Work Orders &amp; Invoices?</span>
						    <%end%> 
					    </p>
					    <p style="">
					    	<%= link_to "Delete Work Item",delete_service_path(service_name),:class=>"button remove",:data=> {confirm: "Are you sure you wish to delete #{service_name.name}?"}%>
					       <%= submit_tag "Update",:class=>"model_save_button save save-new-btn1"%>
					      <button type="button" class="model_cancel_button pull-right" data-dismiss="modal">Cancel</button>
					    </p>					    
					  <%end%>
					</div>
				</div>
			</div>
		</div>
	<% else %>
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header new-modal-header">
	        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Edit <%= service_name.name rescue '' %></h4>
	      </div>
	      <div class="modal-body">
	      	<div class="content">
					  <%= form_tag update_service_path(service_name) ,:class=>"compressed_form work_item" do%>
					   
					    <p>
					      <label for="work_item_name" class="large">Name</label>
					      <%= text_field_tag "work_item[name]",nil,:value=>service_name.name,:class=>"large name", :id=>"work_item_name"%>
					    </p>
					    <p>
					      <label for="work_item_description">Description</label>
					      <%= text_area_tag "work_item[description]",service_name.description,:cols=>"50",:id=>"work_item_description" %>
					    </p>
					    <p>
					    	<label for="work_item_default_unit_cost">Default Unit Cost $</label>
					      <%= text_field_tag "work_item[unit_cost]",nil,:value=>service_name.unit_cost,:class=>"large name", :placeholder=>"0.00", :id=>"work_item_default_unit_cost"%>
					    </p>
					    <p>
					    	<% if service_name.non_taxable %>
						      <input type="hidden" value="0" name="work_item[non_taxable]"><input type="checkbox" value="1" name="work_item[non_taxable]" id="work_item_nontaxable" checked="checked">
						      <label for="work_item_nontaxable">Non-taxable?</label>
						      <span class="description">Should this item be exempt from tax?</span>
						    <%else%>
						   	 	<input type="hidden" value="0" name="work_item[non_taxable]"><input type="checkbox" value="1" name="work_item[non_taxable]" id="work_item_nontaxable">
						      <label for="work_item_nontaxable">Non-taxable?</label>
						      <span class="description">Should this item be exempt from tax?</span>
						    <%end%>  
					    </p>
					    <p>
					    	<% if service_name.active %>
						      <input type="hidden" value="0" name="work_item[active]"><input type="checkbox" value="1" name="work_item[active]" id="work_item_visible" checked="checked">
						      <label for="work_item_visible">Active?</label>
						      <span class="description">Should this be an option for Estimate, Work Orders &amp; Invoices?</span>
						    <%else%>
						    	<input type="hidden" value="0" name="work_item[active]"><input type="checkbox" value="1" name="work_item[active]" id="work_item_visible">
						      <label for="work_item_visible">Active?</label>
						      <span class="description">Should this be an option for Estimate, Work Orders &amp; Invoices?</span>
						    <%end%>  
					    </p>
					    <p>
					    	<%= link_to "Delete Work Item",delete_service_path(service_name),:class=>"button remove",:data=> {confirm: "Are you sure you wish to delete #{service_name.name}?"}%>
					       <%= submit_tag "Update",:class=>"model_save_button save save-new-btn1"%>
					      <button type="button" class="model_cancel_button pull-right" data-dismiss="modal">Cancel</button>
					    </p>
					  <%end%>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/home/_visit_report_filter.html.erb
<div id="summary" class="content_align">
  <%= form_tag({:action => "visits_report_summary"}, :id=>"filters", :class=>"compressed_form", remote: true) do %>
    <p>
      <label for="report_completed_Completed">Completed</label>
      <select name="report[completed]" id="report_completed">
        <option value=""></option>
        <option value="Yes">Yes</option>
        <option value="No">No</option>
      </select>
    </p>

    <p>
      <label for="report_assigned_to_Assigned To">Assigned to</label>
      <%= select("report", "assigned_to", [[current_user.full_name, current_user.id],current_user.team_members.map{ |member| [member.full_name, member.member_id]}], {prompt: ''})%>
    </p>

    <p>
      <label for="report_contains_line_item_Contains Line Item">Contains line item</label>
      <select name="report[contains_line_item]" id="report_contains_line_item">
        <option value=""></option>
      </select>
    </p>

    <p>
      <input type="submit" value="Update" name="commit" class="button">
    </p>
  <% end%>
</div>

app/views/home/client_balance_summary.js.erb
$('[data-toggle="popover"]').popover('hide');
$("#client_balance_summary").html("<%= escape_javascript(  render :partial => 'get_client_balance_summary',  :locals => {:@invoice => @invoice} ) %> ")

app/views/home/open_invoice_dialog.js.erb
$('#invoice_payment_modal').html("<%= escape_javascript(  render :partial => 'open_invoice_dialog') %> ");

app/views/home/quotes_report_summary.js.erb
$('[data-toggle="popover"]').popover('hide');
$("#quotes_report_summary").html("<%= escape_javascript(  render :partial => 'get_quotes_report_summary',  :locals => {:@quotes => @quotes} ) %> ")