config/routes.rb
      post "/chemical_used",:to =>'chemicals#chemical_used'
      get "/chemical_display",:to=>"chemicals#chemical_display"
      post "/chemical_test" , :to=>"chemicals#chemical_test"
      get "/view_chemical_result" , :to=>"chemicals#view_chemical_result"
      get "/chemical_test_range", :to=>"chemicals#chemical_test_range"
      get "/service_item", :to=>"chemicals#service_item"
      post "/service_item_create" ,:to=>"chemicals#service_item_create"
      get "/service_item_display", :to=>"chemicals#service_item_display"

      post "/charge_create",:to=>"charges#charge_create"
      post "/update_coordinates",:to=>"trackings#update_coordinates"
      get "/show_points",:to=>"trackings#show_points"
      get "/deactive_points",:to=>"trackings#deactive_points"
      resources :clients do
        member do
          get "client_property" 
          post "update_client"
        end
      end
      resources :jobs do
        collection do
          get "today_schedule"
          get 'signature_job'
        end
        member do
          get "job_invoice"
          post "update_job"
          post "close_job"
          post "job_payment"
          post "reopen_job"
        end
      end
      resources :properties do
        member do
          post "update_property"
        end
      end
      resources :items do
        member do
          post "update_item"
        end
      end
      resources :quotes do
        member do
          post "update_quote"
          get "find_quote"
          post "signature_quote"
          post "quotes_image"
          post "quote_image_save"
        end
      end
      resources :invoices do
        member do
        post "update_invoice" 
        end
      end
      resources :basic_tasks do 
        collection do
          get "today_task"
        end
        member do
          post "update_task"
        end

      end

      resources :timesheets do
        member do
        post "update_timesheet" 
        end
      end

      resources :home do
        collection do
          get "weather"
        end
      end

      resources :expenses do 
        member do   
         post "update_expense"  
        end
      end
    end
  end

  resources :numbers do
    collection do
      post :update_ivr_number
      post :search
    end
  end
  resources :key_actions

  resources :keys

  resources :ivrs do

    collection do
      post 'create_beta'
      post 'add_sub_menu'
      post 'create_feedback'
      post 'check_email'
      post 'key_description'
    end
    member do
      get 'twiml/repeat_menu(/:sub_menu_id)', :to => "ivrs#twiml_repeat_menu" , :as => :twiml_repeat
      get 'twiml(/:sub_menu_id)' , :to => "ivrs#twiml" , :as => :twiml
      get 'handle_recording'
      get 'calls'
      get 'release'
      get 'templates'
      get 'apply_template'
      post 'sms_callback'
      get 'analytics'
      post 'filters'
    end
  end

  get "action_types" => 'action_types#index'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash

    end
    collection do
      get :notify
      get :update_notify
      get :display_notify
    end

  end
  resources :classifieds do
    member do
      get :media
      patch :media_save
      post :media_save
    end 
  end

  resources :subscriptions do 
    collection do
      get :plan
      post :change_plan
      post :downgrade_plan
    end
  end
  resources :maps do
    collection do
      get :zoom
      get :optimize 
      get :assigned_team
      get :change_assign
      post :reassign
      get :map_show
      post :property_estimate
      get :lead
      get :add_marker
      post :display_address
      get :create_lead
      post :add_lead
    end
  end 
  resources :quotes
  resources :notifications 

  resources :events do
    collection do
      get :to_dos
      post :move
      post "visit_complete_event/:visit_id" => "events#visit_complete_event", as: "visit_complete_event" 
      get "visit_view_detail_event/:visit_id" => "events#visit_view_detail_event", as: "visit_view_detail_event"
      get "edit_visit_event/:visit_id" => "events#edit_visit_event", as: "edit_visit_event"
      post "update_visit_event/:visit_id" =>  "events#update_visit_event", as: "update_visit_event"
      get "destroy_visit_event/:job_id/:visit_id" =>  "events#destroy_visit_event", as: "destroy_visit_event"
      get 'new_job_event' => 'events#new_job_event', as: 'new_job_event'
      post 'search_job_client' => 'events#search_job_client', as: 'search_job_client'
    end
    get :view_detail
  end

  resources :basic_tasks do
    collection do
      get :to_dos 
      post :move
    end
    post :complete_basic_task
    get :view_detail
  end

  resources :jobs do 
    collection do 
      get "recurring_job"
    end
  end
  resources :properties do
    member do
      get :manually_geocode
      post "update_property"
    end
    collection do
      post :location_update
      post :property_service_plan
      post :pool_update_active
      get :convert_client
      post :converted
      get :lead_message
      post :lead_message_pdf
      post :property_tag
      post :tag_delete
      post :templates_display
      get :email_message
      post :message_email_sent
      get :lead_mailer
    end
  end

  resources :spa_pooles do 
    collection do
      get :property_pool_data
      post :pool_data_create
      post :pool_data_update
      get :pool_data_edit
      get :spa_data
      post :spa_data_create
      get :spa_data_edit
      post :spa_data_update
      post :calculate_gallonage
      post :calculate_spa_volume
      post :pool_shape_change
      post :spa_shape_change
    end
  end

  get "/dashboard" =>"dashboards#dashboard"
  get "/get_summary_data" =>"dashboards#get_summary_data"
  get "/get_quick_links"  =>"dashboards#get_quick_links"
  get "/weather_data"  =>"dashboards#weather_data"

  resources :clients do
    collection do
      get :demo_deactive 
      get :new_client
    end
    member do
      post :payment
    end
  end

  resources :documents do
    collection do
      get :document_box
      get :document_setting
      post :document_check
    end
    member do
      get :download
      get :delete_account # admin delete its account
    end
  end

  resources :intuits do
    collection do
      get :authenticate
      get :oauth_callback
      get :closed_qb_account
    end
  end

  resources :email_notifications do
    collection do
      get 'reply_message' 
      post 'message_create' 
      get 'thanks_message'
      post 'email_read'
      get 'chat_popup'
    end
  end

  resources :timesheets do 
    collection do
      get 'prev_day'
      get 'next_day'
      get 'category_new'
      get 'payroll'
      get 'prev_payroll'
      get 'next_payroll'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end
  end
  resources :expenses do
    collection do
      get 'mile_category' , :as => "expenses/mileage"
      post 'create_mileage'
      post 'category_create'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end

  end
  resources :pool_services do 
    collection do 
      get "pool_service"
      get "spa_service"
      post "service_create"
      get "chemical_items"
      post "chemical_items_create" 
      get "pool_chemical_test"
      post "check_pool_test"
      get "chemical_used"
      post "chemical_used_create"
      get "service_items"
      post "service_items_create"
      get "market_source"
      post "source_create"
      post "source_update"
      get "service_plan"
      post "service_plan_create"
      post "service_plan_update"
      get :service_plan_label
      post :update_plan_label
    end
    member do
      get "source_edit"
      get "source_delete"
      get "service_plan_edit"
      get "service_plan_delete"
    end
  end
  resources :chamicals
  resources :postcards, only: [:index, :create] 
  devise_for :users, :controllers => {:sessions=>"sessions",:confirmations=>"confirmations",:registrations => "registrations",:passwords=>"passwords",:omniauth_callbacks => "omniauth_callbacks"}
  

  post '/twilio_call' =>"communications#twilio_call"
  post '/twilio_connect' =>"communications#twilio_connect"
  post '/property_note' =>"communications#property_note"
  post '/property_email' =>"communications#property_email"
  post '/property_sms'   =>"communications#property_sms"
  get '/more_activity'   =>"communications#more_activity"
  get '/edit_note_activity' =>"communications#edit_note_activity"
  post '/update_note_activty' =>"communications#update_note_activty"
  get '/filter_activity' =>"communications#filter_activity"
  post '/call_activity' =>"communications#call_activity"

  get "/communication_header" =>"communications#communication_header"

  resources :vendors do 
    collection do
      post :import_vendor
      get :vendor_setting
      get :import_file
      post :vendor_customize
      post :search_vendors
      get :preference_vendors
      get :add_preference
    end
  end

  resources :chats do
    resources :chat_messages
  end

  get '/backup' => "back_ups#back_check" ,:as=>"backup"
  get '/manage_data' => "back_ups#manage_data" ,:as=>"manage_data"
  get '/csv_generate' => "back_ups#csv_generate" ,:as=>"csv_generate"
  post '/csv_import' => "back_ups#csv_import" ,:as=>"csv_import"
  get '/csv_upload' => "back_ups#csv_upload" ,:as=>"csv_upload"
  get '/download_template' => "back_ups#download_template" ,:as=>"download_template"

  get '/leads' => "leads#view_lead"
  get '/import_lead' => "leads#import_lead"
  post '/import_file' => "leads#import_file"

  post 'quotes/new'
  post 'jobs/new'
  post 'properties/new'
  post 'invoices/new'
  root 'home#index'
  post 'clients/create'
  post '/call' => "home#call"
  post '/connect' => "home#connect"

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
	include SubscriptionsHelper
	protect_from_forgery with: :null_session

	def plan
	end

#change subscription plan
	def change_plan
		@plan_view = pricing_plan_change(current_user,params)
		@charge=Charge.where("user_id =? AND account_status= ?",current_user.id,current_user.plan_type).last
	  if @charge.blank?
	  	 @base_charge= plan_type_price(params)
	  else
	  	plan_choose= amount_type_price(params)
	  	amount = plan_choose - @plan_view
	  	@base_charge = (amount/100).round(2)
	  end
	end

#downgrade subscription plan
	def downgrade_plan
		charge=Charge.where("user_id =? AND account_status= ?",current_user.id,current_user.plan_type).last
		transaction = Stripe::Charge.retrieve(charge.transaction_id)
    sucess_refund=transaction.refunds.create(:amount=>(params[:amount].to_f*100).to_i) rescue false    
    if sucess_refund
    	current_user.plan_type = params[:plan_type]
    	current_user.save
    	redirect_to plan_subscriptions_path ,:notice=>"Your plan is downgrade"
    else
    	redirect_to plan_subscriptions_path ,:notice=>"Your are able to downgrade after #{charge.active_date+7}"
    end
	end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
	def plan_activation_solo(user)
		if user.plan_type== "solo"
      "solo_active"
		end
	end

	def plan_activation_team(user)
		if user.plan_type== "team"
      "team_active"
		end
	end

	def plan_activation_business(user)
		if user.plan_type== "business"
      "business_active"
		end
	end


	def pricing_plan_change(user,params)
		current_plan = current_user.plan_type 
		change_plan = params[:plan_type]
		charge_present=Charge.where("user_id =? AND account_status= ?",current_user.id,current_user.plan_type).last
		
		if current_plan == "solo"
		  if charge_present.blank?
		  	if current_user.created_at.to_date+ 15 > Date.today
		  		current_user.plan_type=change_plan
		  		current_user.save
		  	else
		  		return false
		  	end
		  else
		  	active_date=charge_present.active_date
		  	day_used=(Date.today-active_date).to_i
		  	amount=1995
		  	per_day= amount.to_f/30
		  	used_plan = per_day * day_used
		  	amount_remaining = amount - used_plan
		  end
		elsif current_plan == "team"
			if charge_present.blank?
		  	if current_user.created_at.to_date+ 15 > Date.today
		  		current_user.plan_type=change_plan
		  		current_user.save
		  	else
		  		return false
		  	end
		  else
		  	active_date=charge_present.active_date
		  	day_used=(Date.today-active_date).to_i
		  	amount=2995
		  	per_day= amount.to_f/30
		  	used_plan = per_day * day_used
		  	amount_remaining = amount - used_plan
		  end
		elsif current_plan == "business"
			if charge_present.blank?
		  	if current_user.created_at.to_date+ 15 > Date.today
		  		current_user.plan_type=change_plan
		  		current_user.save
		  	else
		  		return false
		  	end
		  else
		  	active_date=charge_present.active_date
		  	day_used=(Date.today-active_date).to_i
		  	amount=4995
		  	per_day= amount.to_f/30
		  	used_plan = per_day * day_used
		  	amount_remaining = amount - used_plan
		  end
		end	
	end



	def plan_type_price(params)
		if params[:plan_type]=="solo"
			amount="19.95"
		elsif params[:plan_type]=="team"
			amount="29.95"
		elsif params[:plan_type]=="business"
			amount="49.95"
		end 
	end


	def amount_type_price(params)
		if params[:plan_type]=="solo"
			amount=1995
		elsif params[:plan_type]=="team"
			amount=2995
		elsif params[:plan_type]=="business"
			amount=4995
		end 
	end
end

app/views/subscriptions/_new_payment.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header new-modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
        <h4 class="modal-title" id="myModalLabel">Billing</h4>
      </div>
      <div class="modal-body">
          <p style="pading:10px;">
            <%if current_user.plan_type.blank?%>
              You just select <b><%= params[:plan_type] %></b> plan , Please billing to confirm this plan.
            <%else%>
              Current you used this plan <b><%= current_user.plan_type.capitalize %></b> and now you are upgrade your plan <b><%= params[:plan_type].capitalize%></b> So your payment is auto adjusted , So please pay remaining account to upgrade your plan
            <%end%>
          </p>
            
        <div id="account_details" class="fieldset billing_information">
          <div class="">
            <% if current_user.confirmed? %>
              <%= form_tag charges_create_path,:id=>"stripe-form" do%>
              <p>
                <label for="billing_info_name">Amount</label>
                <%= text_field_tag "base_charge", nil, value: @base_charge,:readonly=>true %></p>
                <p>
                  <label for="billing_info_name">Name on Card</label>
                
                  <%= text_field_tag "charge[name]",nil,value: @charge.blank? ? "" : @charge.name,:id=>"billing_info_name"%>
                </p>
                <%= hidden_field_tag "type",nil,:value=>params[:plan_type]%>
                <p>
                  <label for="billing_info_card_number">Card Number</label>
                  <%= text_field_tag "charge[card_number]",nil,:value=>@charge.blank? ? "" : @charge.card_number,:id=>"billing_info_card_number"%>
                  <img src="//d3ey4dbjkt2f6s.cloudfront.net/assets/app/icons/visa_48x29-78bbf7cfbc3ee34db0daf60b8b77a8dc.png" alt="Visa 48x29">
                  <img src="//d3ey4dbjkt2f6s.cloudfront.net/assets/app/icons/master_card_48x29-a6ebc0f3002c83d72e8f6e43d1a0c362.png" alt="Master card 48x29">
                </p>

                <p>
                  <label for="billing_info_exp_month">Expiry</label>
                 <%= select_tag("charge[exp_month]", options_for_select([["1","1"],["2","2"], ["3","3"], ["4","4"],["5","5"], ["6","6"], ["7","7"], ["8","8"],["9","9"],["10","10"],["11","11"],["12","12"]],:selected=>@charge.blank? ? "" : @charge.exp_month),:style=>"width: 50px;")%>
                 	<%= select_year(@charge.blank? ? Date.today : @charge.exp_year, :start_year => Time.now.year, :end_year => Time.now.year + 15, :field_name => "exp_year", :prefix => :charge)%>
                </p>
                <br>
                <p>
                  <label for="billing_info_ccv">CVC</label>
                  <%= text_field_tag "charge[cvc]",nil,:value=>@charge.blank? ? "" : @charge.cvc,:id=>"billing_info_ccv",:style=>"width: 50px;"%>
                </p>
                <br>
                <p>
                  <label for="billing_info_address1">Address 1</label>
                  <%= text_field_tag "charge[address1]",nil,:value=>@charge.blank? ? "" : @charge.address1,:id=>"billing_info_address1"%>
                  <br><span style="margin-left: 140px;" class="description">* as it appears on your credit card statement</span>
                </p>

                <p>
                  <label for="billing_info_address2">Address 2</label>
                  <%= text_field_tag "charge[address2]",nil,:value=>@charge.blank? ? "" : @charge.address2,:id=>"billing_info_address2"%> 
                </p>

                <p>
                  <label for="billing_info_city">City</label>
                  <%= text_field_tag "charge[city]",nil,:value=>@charge.blank? ? "" : @charge.city,:id=>"billing_info_city"%>
                </p>

                <p>
                  <label for="billing_info_state">State/Province</label>
                  <%= text_field_tag "charge[state]",nil,:value=>@charge.blank? ? "" : @charge.state,:id=>"billing_info_state"%>
                </p>

                <p>
                  <label for="billing_info_country">Country</label>
                  <%= country_select_tag "charge[country]", {priority: %w(US CA), prompt: 'Please select a country',:selected=>@charge.blank? ? "" : @charge.country},:class=>"billing_country" ,:style=>"width: 350px;"%>
                </p>

                <p>
                  <label for="billing_info_zip">Zip/Postal Code</label>
                  <%= text_field_tag "charge[zip_code]",nil,:value=>@charge.blank? ? "" : @charge.zip_code,:id=>"billing_info_zip"%>
                </p>
                <br>
                <p>
                  <label for="billing_info_email">Billing E-mail</label>
                  <%= text_field_tag "charge[email]",nil,:value=>current_user.email,:id=>"billing_info_email"%>
                  <span class="description">for your invoices</span>
                </p>

              <%end%>

             <div class="row text-right">
              <button type="button" class="model_cancel_button" data-dismiss="modal">CANCEL</button>
              <input type="submit" value="Submit" style="float:right" name="commit" class="update_button_setting save spin_on_click" id="stripe_button_submit">
             </div>

            <% else %>
              <p class="flash flash_warning" style="width:auto !important;">
                You must verify your e-mail before you enter your credit card. If you did not receive a Welcome Email, <%= link_to 'click here', new_user_confirmation_path, style: "color:blue;" %>.
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<script>
stripeTokenGenerateTest()
</script>

app/views/subscriptions/_refund_payment.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
      <h4 class="modal-title" id="myModalLabel">Downgrade Plan</h4>
    </div>
    <div class="modal-body">
     <p style="pading:10px;">Current you used this plan <b><%= current_user.plan_type.capitalize %></b> and now you are downgrade your plan <b><%= params[:plan_type].capitalize%></b> So your remaining amounty is <b><%= @base_charge.abs %></b> will refund. </p>
      <%= form_tag downgrade_plan_subscriptions_path do %>
        <%= hidden_field_tag "amount",nil,:value=> @base_charge.abs %>
        <%= hidden_field_tag "plan_type",nil,:value=> params[:plan_type] %>
        <%= submit_tag "Down Grad plan",:class=>"button",:data => {:confirm => 'Are you sure downgrade your plan?'},:style=>"margin:52px 144px; padding:12px;"%>
      <%end%>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/subscriptions/change_plan.js.erb
<%if @base_charge.to_f < 0%>
	$("#payment_pay").html("<%= escape_javascript(render 'subscriptions/refund_payment') %>");
<%else%>
	$("#payment_pay").html("<%= escape_javascript(render 'subscriptions/new_payment') %>");
<%end%>
$("#payment_pay").modal("show");

app/views/subscriptions/plan.html.erb
<body class="pricing-page">    
  <div class="client_index">
  <div class="main_container">
    <!-- ******PRICE PLAN****** --> 
    <%= render "clients/error_message_and_flash" %>
    <section id="price-plan" class="price-plan-chat section">
      <div class="container text-center">
        <h2 class="title">15 day FREE trial with all plans!</h2>
        <p class="intro">CopperService's pricing is simple and you can change your plan at any time. </p>
        <div class="price-cols row">
          <div class="col-md-4 col-xs-12 price-tag <%= plan_activation_solo(current_user)%>">
            <%= form_tag change_plan_subscriptions_path,:method=>"post" ,:remote=>true do %>
            <div class="item col-md-12 col-sm-12 col-xs-12">  
              <h3 class="heading">SOLO</h3>
              <div class="content">
                <p class="price-figure"><span class="currency">$</span><span class="number">19.95</span><span class="unit">/month</span></p>
                <ul class="list-unstyled feature-list">
                  <li>1 user</li>
                  <li>Client Unlimited</li>
                  <li>Email Notification yes</li>
                  <li>10 Gb</li>
                </ul>
                <%= hidden_field_tag "plan_type" ,"solo"%>

                <%if current_user.plan_type.blank?%>
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Choose Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type=="solo"%>
                  <%= link_to "#",:class=>"btn btn-cta btn-cta-primary" do %>Selected Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%else%>  
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Down Grade Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%end%>
              </div>
            </div>  <!--//content--> 
            <%end%> 
          </div><!--//item--> 

          <div class="col-md-4 price-tag col-xs-12 <%= plan_activation_team(current_user)%>">
            <%= form_tag change_plan_subscriptions_path ,:method=>"post" ,:remote=>true do %> 
            <div class="item col-md-12 col-sm-12 col-xs-12">       
              <h3 class="heading">TEAM <span class="label label-custom">Popular</span></h3>
              <div class="content">
                <p class="price-figure"><span class="currency">$</span><span class="number">29.95</span><span class="unit">/month</span></p>
                <ul class="list-unstyled feature-list">
                  <li>5 users</li>
                  <li>Client Unlimited</li>
                  <li>Email Notification yes</li>
                  <li>25 Gb</li>
                </ul>
                <%= hidden_field_tag "plan_type" ,"team"%>
                <%if current_user.plan_type.blank?%>
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Choose Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type=="team"%>
                  <%= link_to "#",:class=>"btn btn-cta btn-cta-primary" do %>Selected Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type=="solo"%>
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Upgrade Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type=="business"%>  
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Down Grade Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%end%>

              </div>
            </div><!--//content-->
            <%end%>
          </div><!--//item--> 

          <div class="col-md-4 price-tag col-xs-12 <%= plan_activation_business(current_user)%>">
            <%= form_tag change_plan_subscriptions_path ,:method=>"post" ,:remote=>true  do %> 
            <div class="item col-md-12 col-sm-12 col-xs-12">   
              <h3 class="heading">BUSINESS</h3>
              <div class="content">
                <p class="price-figure"><span class="currency">$</span><span class="number">49.95</span><span class="unit">/month</span></p>
                <ul class="list-unstyled feature-list">
                  <li>20 Each additional user $2</li>
                  <li>Client Unlimited</li>
                  <li>Email Notification yes</li>
                  <li>100 Gb</li>
                </ul>
                <%= hidden_field_tag "plan_type" ,"business"%>
                <%if current_user.plan_type.blank?%>
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Choose Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type=="business"%>
                  <%= link_to "#",:class=>"btn btn-cta btn-cta-primary" do %>Selected Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type =="team"%>
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Upgrade Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%elsif current_user.plan_type =="solo"%>  
                  <%= button_tag :class=>"btn btn-cta btn-cta-primary" do %>Upgrade Plan<br/>
                    <span class="extra">30 day free trial</span>
                  <%end%>
                <%end%>
              </div>
            </div><!--//content-->
            <%end%>
          </div><!--//item-->   
        </div><!--//row-->
      </div>
    </div><!--//container-->
  </section><!--//price-plan-->     
  </div><!--//wrapper-->
  <div class="modal fade" id="payment_pay" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;"></div>         
</body>
</html> 


<style type="text/css">
ul.list-unstyled.feature-list {
  list-style: none;
}
.price-tag{
  width: 30% !important;
}
</style>