config/routes.rb
Rails.application.routes.draw do

  
  resources :service_reminders

  resources :services

  resources :fuels

  resources :vehicles
  post 'pusher/auth'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invoices
  resources :supports
  resources :items do
    collection do
      get "inventory_head" 
      post "inventory_update"
    end
  end
  resources :parts
  namespace :api do
    namespace :v1 do
      post "/sign_in", :to => 'sessions#create'
      delete "/sign_out", :to => 'sessions#destroy'
      post "/sign_up", :to => 'registrations#create'
      post "/users/password", :to => 'passwords#create'
      get "/dashboards/username",:to =>'dashboards#username'
      get "/conversations/chat_user",:to =>'conversations#chat_user'
      post "/conversations/conversation_user",:to =>'conversations#conversation_user'
      post "/conversations/create",:to =>'conversations#create'
      get "/conversations/show_message",:to =>'conversations#show_message'
      get "/dashboards/weather",:to =>'dashboards#weather'
      get "/chemical_add",:to =>'chemicals#chemical_add'
      post "/chemical_used",:to =>'chemicals#chemical_used'
      get "/chemical_display",:to=>"chemicals#chemical_display"
      post "/chemical_test" , :to=>"chemicals#chemical_test"
      get "/view_chemical_result" , :to=>"chemicals#view_chemical_result"
      get "/chemical_test_range", :to=>"chemicals#chemical_test_range"
      get "/service_item", :to=>"chemicals#service_item"
      post "/service_item_create" ,:to=>"chemicals#service_item_create"
      get "/service_item_display", :to=>"chemicals#service_item_display"

      post "/charge_create",:to=>"charges#charge_create"
      post "/update_coordinates",:to=>"trackings#update_coordinates"
      get "/show_points",:to=>"trackings#show_points"
      get "/deactive_points",:to=>"trackings#deactive_points"
      resources :clients do
        member do
          get "client_property" 
          post "update_client"
        end
      end
      resources :jobs do
        collection do
          get "today_schedule"
          get 'signature_job'
        end
        member do
          get "job_invoice"
          post "update_job"
          post "close_job"
          post "job_payment"
          post "reopen_job"
        end
      end
      resources :properties do
        member do
          post "update_property"
        end
      end
      resources :items do
        member do
          post "update_item"
        end
      end
      resources :quotes do
        member do
          post "update_quote"
          get "find_quote"
          post "signature_quote"
          post "quotes_image"
          post "quote_image_save"
        end
      end
      resources :invoices do
        member do
        post "update_invoice" 
        end
      end
      resources :basic_tasks do 
        collection do
          get "today_task"
        end
        member do
          post "update_task"
        end

      end

      resources :timesheets do
        member do
        post "update_timesheet" 
        end
      end

      resources :home do
        collection do
          get "weather"
        end
      end

      resources :expenses do 
        member do   
         post "update_expense"  
        end
      end
    end
  end

  resources :numbers do
    collection do
      post :update_ivr_number
      post :search
    end
  end
  resources :key_actions

  resources :keys

  resources :ivrs do

    collection do
      post 'create_beta'
      post 'add_sub_menu'
      post 'create_feedback'
      post 'check_email'
      post 'key_description'
    end
    member do
      get 'twiml/repeat_menu(/:sub_menu_id)', :to => "ivrs#twiml_repeat_menu" , :as => :twiml_repeat
      get 'twiml(/:sub_menu_id)' , :to => "ivrs#twiml" , :as => :twiml
      get 'handle_recording'
      get 'calls'
      get 'release'
      get 'templates'
      get 'apply_template'
      post 'sms_callback'
      get 'analytics'
      post 'filters'
    end
  end

  get "action_types" => 'action_types#index'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash

    end
    collection do
      get :notify
      get :update_notify
      get :display_notify
    end

  end
  resources :classifieds do
    member do
      get :media
      patch :media_save
      post :media_save
    end 
  end

  resources :subscriptions do 
    collection do
      get :plan
      post :change_plan
      post :downgrade_plan
    end
  end
  resources :maps do
    collection do
      get :zoom
      get :optimize 
      get :assigned_team
      get :change_assign
      post :reassign
      get :map_show
      post :property_estimate
      get :lead
      get :add_marker
      post :display_address
      get :create_lead
      post :add_lead
    end
  end 
  resources :quotes
  resources :notifications 

  resources :events do
    collection do
      get :to_dos
      post :move
      post "visit_complete_event/:visit_id" => "events#visit_complete_event", as: "visit_complete_event" 
      get "visit_view_detail_event/:visit_id" => "events#visit_view_detail_event", as: "visit_view_detail_event"
      get "edit_visit_event/:visit_id" => "events#edit_visit_event", as: "edit_visit_event"
      post "update_visit_event/:visit_id" =>  "events#update_visit_event", as: "update_visit_event"
      get "destroy_visit_event/:job_id/:visit_id" =>  "events#destroy_visit_event", as: "destroy_visit_event"
      get 'new_job_event' => 'events#new_job_event', as: 'new_job_event'
      post 'search_job_client' => 'events#search_job_client', as: 'search_job_client'
    end
    get :view_detail
  end

  resources :basic_tasks do
    collection do
      get :to_dos 
      post :move
    end
    post :complete_basic_task
    get :view_detail
  end

  resources :jobs do 
    collection do 
      get "recurring_job"
    end
  end
  resources :properties do
    member do
      get :manually_geocode
      post "update_property"
    end
    collection do
      post :location_update
      post :property_service_plan
      post :pool_update_active
      get :convert_client
      post :converted
      get :lead_message
      post :lead_message_pdf
      post :property_tag
      post :tag_delete
      post :templates_display
      get :email_message
      post :message_email_sent
      get :lead_mailer
    end
  end

  resources :spa_pooles do 
    collection do
      get :property_pool_data
      post :pool_data_create
      post :pool_data_update
      get :pool_data_edit
      get :spa_data
      post :spa_data_create
      get :spa_data_edit
      post :spa_data_update
      post :calculate_gallonage
      post :calculate_spa_volume
      post :pool_shape_change
      post :spa_shape_change
    end
  end

  get "/dashboard" =>"dashboards#dashboard"
  get "/get_summary_data" =>"dashboards#get_summary_data"
  get "/get_quick_links"  =>"dashboards#get_quick_links"
  get "/weather_data"  =>"dashboards#weather_data"

  resources :clients do
    collection do
      get :demo_deactive 
      get :new_client
    end
    member do
      post :payment
    end
  end

  resources :documents do
    collection do
      get :document_box
      get :document_setting
      post :document_check
    end
    member do
      get :download
      get :delete_account # admin delete its account
    end
  end

  resources :intuits do
    collection do
      get :authenticate
      get :oauth_callback
      get :closed_qb_account
    end
  end

  resources :email_notifications do
    collection do
      get 'reply_message' 
      post 'message_create' 
      get 'thanks_message'
      post 'email_read'
      get 'chat_popup'
    end
  end

  resources :timesheets do 
    collection do
      get 'prev_day'
      get 'next_day'
      get 'category_new'
      get 'payroll'
      get 'prev_payroll'
      get 'next_payroll'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end
  end
  resources :expenses do
    collection do
      get 'mile_category' , :as => "expenses/mileage"
      post 'create_mileage'
      post 'category_create'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end

  end
  resources :pool_services do 
    collection do 
      get "pool_service"
      get "spa_service"
      post "service_create"
      get "chemical_items"
      post "chemical_items_create" 
      get "pool_chemical_test"
      post "check_pool_test"
      get "chemical_used"
      post "chemical_used_create"
      get "service_items"
      post "service_items_create"
      get "market_source"
      post "source_create"
      post "source_update"
      get "service_plan"
      post "service_plan_create"
      post "service_plan_update"
      get :service_plan_label
      post :update_plan_label
    end
    member do
      get "source_edit"
      get "source_delete"
      get "service_plan_edit"
      get "service_plan_delete"
    end
  end
  resources :chamicals
  resources :postcards, only: [:index, :create] 
  devise_for :users, :controllers => {:sessions=>"sessions",:confirmations=>"confirmations",:registrations => "registrations",:passwords=>"passwords",:omniauth_callbacks => "omniauth_callbacks"}
  

  post '/twilio_call' =>"communications#twilio_call"
  post '/twilio_connect' =>"communications#twilio_connect"
  post '/property_note' =>"communications#property_note"
  post '/property_email' =>"communications#property_email"
  post '/property_sms'   =>"communications#property_sms"
  get '/more_activity'   =>"communications#more_activity"
  get '/edit_note_activity' =>"communications#edit_note_activity"
  post '/update_note_activty' =>"communications#update_note_activty"
  get '/filter_activity' =>"communications#filter_activity"

app/models/pool_service.rb
class PoolService < ActiveRecord::Base
	belongs_to :user
end

app/helpers/pool_services_helper.rb
module PoolServicesHelper

	def pool_test_chlorine(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.chlorine.to_i.between?(pool_service.ch_low.to_i,pool_service.ch_high.to_i)
			return "true"
		else
			return "false"
		end
	end

	def pool_test_ph(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.ph_value.to_i.between?(pool_service.ph_low.to_i,pool_service.ph_high.to_i)
			return "true"
		else
			return "false"
		end
	end

	def pool_test_salt(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.salt_level.to_i.between?(pool_service.salt_low.to_i,pool_service.salt_high.to_i)
			return "true"
		else
			return "false"
		end
	end

	def pool_test_calcium(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.calcium_hardness.to_i.between?(pool_service.calcium_hardness_low.to_i,pool_service.calcium_hardness_high.to_i)
			return "true"
		else
			return "false"
		end
	end

	def pool_test_alkalinity(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.total_alkalinity.to_i.between?(pool_service.alkalinity_low.to_i,pool_service.alkalinity_high.to_i)
			return "true"
		else
			return "false"
		end		
	end

	def pool_range_chlorine(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.chlorine.to_i.between?(pool_service.ch_low.to_i,pool_service.ch_high.to_i)
			return ""
		else
			return "Correct Range: #{pool_service.ch_low.to_f} - #{pool_service.ch_high.to_f} "
		end
	end

	def pool_range_ph(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.ph_value.to_i.between?(pool_service.ph_low.to_i,pool_service.ph_high.to_i)
			return ""
		else
			return "Correct Range: #{pool_service.ph_low.to_f} - #{pool_service.ph_high.to_f} "
		end
	end

	def pool_range_salt(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.salt_level.to_i.between?(pool_service.salt_low.to_i,pool_service.salt_high.to_i)
			return ""
		else
			return "Correct Range: #{pool_service.salt_low.to_f} - #{pool_service.salt_high.to_f} "
		end
	end

	def pool_range_calcium(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.calcium_hardness.to_i.between?(pool_service.calcium_hardness_low.to_i,pool_service.calcium_hardness_high.to_i)
			return ""
		else
			return "Correct Range: #{pool_service.calcium_hardness_low.to_f} - #{pool_service.calcium_hardness_high.to_f} "
		end
	end

	def pool_range_alkalinity(pool_test,pool_service)
		if pool_test.id.blank? || pool_service.blank?
			return ""
		elsif pool_test.total_alkalinity.to_i.between?(pool_service.alkalinity_low.to_i,pool_service.alkalinity_high.to_i)
			return ""
		else
			return "Correct Range: #{pool_service.alkalinity_low.to_f} - #{pool_service.alkalinity_high.to_f} "
		end		
	end

end

app/views/pool_services/_1service_items.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header new-modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel">Service Items</h4>
		</div>
		<div class="modal-body">
			<%= form_for(@service_items,:url=>service_items_create_pool_services_path) do |f| %>
				<table border="0" class="service-items">
					<tr>
						<td><label>Filter Cleaned</label></td>
						<td ><%= f.check_box :filter_cleaned%></td>
					</tr>

					<tr>
						<td><label>Netted Surface Debris</label></td>
						<td><%= f.check_box :netted_surface_debris%></td>
					</tr>

					<tr>
						<td><label>Brushed Walls and Steps</label></td>
						<td><%= f.check_box :brushed_walls_steps%></td>
					</tr>	
					
					<tr>
						<td><label>Cleaned Skimmer Baskets</label></td>
						<td><%= f.check_box :cleaned_skimmer_baskets%></td>
					</tr>

					<tr>
						<td><label>Cleaned Pump Basket</label></td>
						<td><%= f.check_box :cleaned_pump_basket%></td>
					</tr>	

					<tr>
						<td><label>Vacuumed Pool</label></td>
						<td><%= f.check_box :vacuumed_pool%></td>
					<tr>

					<tr>
						<td><label>Checked Water Level</label></td>
						<td><%= f.check_box :checked_water_level%></td>
					</tr>

					<tr>
						<td><label>Inspected Pump</label></td>
						<td><%= f.check_box :inspected_pump%></td>
					</tr>

					<tr>
						<td><label>Notes to Customer</label></td>
						<td><%= f.text_area :notes_to_customer%></td>
					</tr>

					<tr>
						<td><label>Complete</label></td>
						<td><%= f.radio_button :status, 'complete'%></td>
					</tr>

					<tr>
						<td><label>InComplete</label></td>
						<td><%= f.radio_button :status, 'incomplete'%></td>
					</tr>

					<tr>
						<td><label>Waiting for parts</label></td>
						<td><%= f.radio_button :status, 'waiting_parts'%></td>
					</tr>

					<tr>
						<td>SMS</td>
						<td><%= radio_button_tag "send" ,"sms"%></td>
					</tr>

					<tr>
						<td>Email</td>
						<td><%= radio_button_tag "send","email"%></td>
					</tr>
					<%= f.hidden_field :user_id ,:value=>current_user.id%>
					<%= f.hidden_field :property_id ,:value=>params[:property_id]%>
					<%= hidden_field_tag "service_type",nil,:value=>"service_items"%>
				</table>
				<br>
				<button type="button" class="model_cancel_button pull-right" data-dismiss="modal">Close</button>	
				<%= f.submit "submit",:class=>"update_button_setting save-new-btn1",:style=>"float:right;"%>
			<% end %>
		</div> 		
	</div>
</div>

<style type="text/css">
.service-items{
width: 80% !important;
}
</style>

app/views/pool_services/_market_source.html.erb
<%if !@market_sources.blank? %>
	<%@market_sources.each_with_index do |source,index|%>
		<div class="row">
			<div id="popover_form_content">
				<div class="span2" id="popover_left">
				</div>
				<div class="span2"  id="popover_left">
					<%= index+1 %>. &nbsp;&nbsp;<%= source.source_name%>
				</div>
				<div class="span2"  id="popover_left">
					<%= link_to "Edit",source_edit_pool_service_path(source)%> &nbsp;
					<%= link_to "Delete",source_delete_pool_service_path(source), :data => {:confirm => 'Are you sure?'}%>
				</div>
			</div>
		</div>
	<%end%>
<%end%>

<h1 class="title2-font">Edit Market Sources</h1>

<%= form_tag source_create_pool_services_path ,:class=>"edit_work_configuration compressed_form",:remote=>true do %>
	<div class="row">
		<div id="popover_form_content">
			<div class="span2" id="popover_left">
				<label for="expense_cost">Market Source</label>
			</div> 
			<div class="span3"  id="popover_left">
				<%= text_field_tag "market_source[source_name]", nil,class: "large strong", autofocus: "autofocus" ,:required=>true,:placeholder=>"market source"%>
				<%= hidden_field_tag "market_source[user_id]",nil,value: current_user.id%>
			</div>
		</div>
	</div> 
	<div class="row">
		<%= submit_tag "save",:class=>"update_button_setting save-new-btn1",:style=>"margin-left: 36%;"%>	
	</div>
<%end%>

app/views/pool_services/_service_plan.html.erb
<%if !@service_plans.blank? %>
<h1 class="title1-font"> Service Plan Lists</h1>
	<table class="table"> 
		<thead>
			<tr>
				<th>S.No</th>
				<th>Service Name</th>
				<th>Description</th>
				<th>Unit Cost</th>
				<th colspan="2">Action</th>
			</tr>
	  <thead>	
	  <tbody>
			<%@service_plans.each_with_index do |plan,index|%>
				<tr>
					<td><%= index+1 %></td>
					<td><%= plan.name%></td>
					<td><%= plan.description%></td>
					<td><%= plan.unit_cost%></td>
					<td><%= link_to "Edit",service_plan_edit_pool_service_path(plan)%></td>
					<td><%= link_to "Delete",service_plan_delete_pool_service_path(plan), :data => {:confirm => 'Are you sure?'}%></td>
				</tr>
			<%end%>
		</tbody>
	</table>	
<%end%>

<h1 class="title2-font" style="display:inline-block">Service Plan</h1>
<%= link_to "Plan Label Edit",service_plan_label_pool_services_path,:class=>"update_button_setting save-new-btn1",:style=>"float:right;"%>
<%=form_for(@service_plan ,:url=>service_plan_create_pool_services_path) do |f|%>
	<%= f.hidden_field :user_id , :value=>current_user.id%>
	<div class="clearfix"></div>
	<div class="row">
		<div>
		<div class="span3">
			<label><%= @plan_label.filter_cleaned.blank? ? "Filter Cleaned" : @plan_label.filter_cleaned%></label>
		</div>
		<div class="span2">
			<%= f.check_box :filter_cleaned%>
		</div>
		<div class="span3">
			<label><%= @plan_label.backwash.blank? ? "Backwash (sand filter)" : @plan_label.backwash %></label>
		</div>
		<div class="span2">
			<%= f.check_box :backwash%>
		</div>
		</div>
		<div class="clearfix"></div>
		<div>
		<div class="span3">
			<label><%= @plan_label.brushed_walls_steps.blank? ? "Brushing walls" : @plan_label.brushed_walls_steps %></label>
		</div>
		<div class="span2">
			<%= f.check_box :brushed_walls_steps%>
		</div>
		<div class="span3">
			<label><%= @plan_label.skimming_surface.blank? ? "Skimming Surface" : @plan_label.skimming_surface%></label>
		</div>
	
		<div class="span2">
			<%= f.check_box :skimming_surface%>
		</div>
		</div>
	<div class="clearfix"></div>
	<div>
		<div class="span3">
			<label><%= @plan_label.waterline_tiles_cleaned.blank? ? "Waterline tiles cleaned" : @plan_label.waterline_tiles_cleaned %></label>
		</div>
		<div class="span2">
				<%= f.check_box :waterline_tiles_cleaned%>
		</div>
		<div class="span3">
			<label><%=@plan_label.cleaned_skimmer_baskets.blank? ? "Cleaned Skimmer Baskets" : @plan_label.cleaned_skimmer_baskets%></label>
		</div>
		<div class="span2" >
			<%= f.check_box :cleaned_skimmer_baskets%>
		</div>
		</div>
	<div class="clearfix"></div>
	<div>

		<div class="span3">
			<label><%=@plan_label.netted_surface_debris.blank? ? "Netted Surface Debris" : @plan_label.netted_surface_debris%></label>
		</div>
		<div class="span2" >
			<%= f.check_box :netted_surface_debris%>
		</div>

		<div class="span3">
			<label><%=@plan_label.floor_vacuumed.blank? ? "Floor vacuumed" : @plan_label.floor_vacuumed%></label>
		</div>

		<div class="span2">
			<%= f.check_box :floor_vacuumed%>
	  </div>
	  </div>
	  <div class="clearfix"></div>
	  <div>
		<div class="span3">
			<label><%=@plan_label.pump_strainer_baskets.blank? ? "Pump strainer baskets" : @plan_label.pump_strainer_baskets%></label>
		</div>

		<div class="span2">
			<%= f.check_box :pump_strainer_baskets%>
		</div>
		
		<div class="span3">
			<label><%=@plan_label.cleaned_pump_basket.blank? ? "Cleaned Pump Basket" : @plan_label.cleaned_pump_basket%></label>		
		</div>

		<div class="span2">
			<%= f.check_box :cleaned_pump_basket%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>

		<div class="span3">
			<label><%=@plan_label.vacuumed_pool.blank? ? "Vacuumed Pool" : @plan_label.vacuumed_pool%></label>
		</div>
		<div class="span2">
			<%= f.check_box :vacuumed_pool%>
		</div>

		<div class="span3">
			<label><%=@plan_label.checked_water_level.blank? ? "Checked Water Level" : @plan_label.checked_water_level%></label>
		</div>
		<div class="span2">
			<%= f.check_box :checked_water_level%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>

		<div class="span3">
			<label><%=@plan_label.inspected_pump.blank? ? "Inspected Pump" : @plan_label.inspected_pump%></label>
		</div>
		<div class="span2">
			<%= f.check_box :inspected_pump%>
		</div>
		<div class="span3">
			<label><%=@plan_label.pool_sweep_cleaner.blank? ? "Pool Sweep / Cleaner" : @plan_label.pool_sweep_cleaner%></label>
		</div>
		<div class="span2">
			<%= f.check_box :pool_sweep_cleaner%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>

		<div class="span3">
			<label><%=@plan_label.net_surface_bottom.blank? ? "NET surface & bottom" : @plan_label.net_surface_bottom%></label>
		</div>
		<div class="span2">
			<%= f.check_box :net_surface_bottom%>
		</div>
		<div class="span3">
			<label><%=@plan_label.inspect_pool_spa_eqip.blank? ? "Inspect Pool & Spa Equipment" : @plan_label.inspect_pool_spa_eqip%></label>
		</div>
		<div class="span2">
			<%= f.check_box :inspect_pool_spa_eqip%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>	

		<div class="span3">
			<label><%=@plan_label.wipe_ladder_handrails.blank? ? "Wipe ladder and handrails" : @plan_label.wipe_ladder_handrails%></label>
		</div>
		<div class="span2">
			<%= f.check_box :wipe_ladder_handrails%>
		</div>
		<div class="span3">
			<label><%=@plan_label.adjust_timeclock.blank? ? "Adjust TimeClock as needed" : @plan_label.adjust_timeclock%></label>
		</div>
		<div class="span2">
			<%= f.check_box :adjust_timeclock%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>

		<div class="span3">
			<label><%=@plan_label.add_water_needed.blank? ? "ADD water  as needed" : @plan_label.add_water_needed%></label>
		</div>
		<div class="span2">
			<%= f.check_box :add_water_needed%>
		</div>
		<div class="span3">
			<label><%=@plan_label.filter_pressure_monitor.blank? ? "Filter Pressure Monitor" : @plan_label.filter_pressure_monitor%></label>
		</div>
		<div class="span2">
			<%= f.check_box :filter_pressure_monitor%>
		</div>
		</div>
	  <div class="clearfix"></div>
	  <div>

		<div class="span3">
			<label><%=@plan_label.notes_to_customer.blank? ? "Customer Note" : @plan_label.notes_to_customer%></label>
		</div>
		<div class="span2">
			<%= f.check_box :notes_to_customer%>
		</div>
	</div>	
</div>
	<div class="clearfix"></div>

	<div class="row" >
		<div style="width:50%; float:left;">
			<%= f.label :name%>
			<%= f.text_field :name%>
		</div>
		<div style="width:50%; float:right;">
			<%=f.label :unit_cost%>
			<%=f.text_field :unit_cost%>
		</div>
	</div>

	<div class="row">
			<%= f.label :description%>
			<%= f.text_area :description,:style=>"width:100%;",rows: "4"%>
	</div>
	<%= f.submit "submit",:class=>"update_button_setting save-new-btn1",:style=>"float:right;"%>
<%end%>

<style type="text/css">

.span3 {
  margin-left: 0px !important;
}
label{
	  text-align: left !important;
}
</style>

app/views/pool_services/market_source.html.erb
<div id="app_wrapper">
  <div class="client_index">
    <div class="main_container">
      <div id="content" style="height: auto;">
        <div class="padding">
          <%=render "home/work_item_side_bar" %>
          <div id="settings_area">
           	<div class="market-source">
							<%= render "market_source"%>
				    </div>
          </div>
        </div>  
      </div>  
    </div>  
  </div>  
</div>  

app/views/pool_services/pool_service.html.erb
<div id="app_wrapper">
  <div class="client_index">
    <div class="main_container">
      <div style="height: auto;">
        <div>
          <%=render "home/work_item_side_bar" %>
          <div id="settings_area">
            <b><h1 class="title2-font"> Pool service Setting</h1></b>
            <%=render "pool_spa_service"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pool_services/service_items.js.erb
$("#service-items").html("<%= escape_javascript(  render :partial => 'pool_services/service_items') %> ");
$('#service-items').modal('show');

app/views/pool_services/service_plan.html.erb
<div id="app_wrapper">
  <div class="client_index">
    <div class="main_container">
      <div id="content" style="height: auto;">
        <div class="padding">
          <%=render "home/work_item_side_bar" %>
          <div id="settings_area">
          	<div class="service-plan">
          		<%= render "pool_services/service_plan"%>
          	</div>
          </div>	
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pool_services/service_plan_label.html.erb
<div id="app_wrapper">
  <div class="client_index">
    <div class="main_container">
      <div id="content" style="height: auto;">
        <div class="padding">
          <%=render "home/work_item_side_bar" %>
          <div id="settings_area">
          	<div class="service-plan">
          		<%= render "pool_services/service_label_edit"%>
          	</div>
          </div>	
        </div>
      </div>
    </div>
  </div>
</div>