config/routes.rb
Rails.application.routes.draw do

  
  resources :service_reminders

  resources :services

  resources :fuels

  resources :vehicles
  post 'pusher/auth'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :invoices
  resources :supports
  resources :items do
    collection do
      get "inventory_head" 
      post "inventory_update"
    end
  end
  resources :parts
  namespace :api do
    namespace :v1 do
      post "/sign_in", :to => 'sessions#create'
      delete "/sign_out", :to => 'sessions#destroy'
      post "/sign_up", :to => 'registrations#create'
      post "/users/password", :to => 'passwords#create'
      get "/dashboards/username",:to =>'dashboards#username'
      get "/conversations/chat_user",:to =>'conversations#chat_user'
      post "/conversations/conversation_user",:to =>'conversations#conversation_user'
      post "/conversations/create",:to =>'conversations#create'
      get "/conversations/show_message",:to =>'conversations#show_message'
      get "/dashboards/weather",:to =>'dashboards#weather'
      get "/chemical_add",:to =>'chemicals#chemical_add'
      post "/chemical_used",:to =>'chemicals#chemical_used'
      get "/chemical_display",:to=>"chemicals#chemical_display"
      post "/chemical_test" , :to=>"chemicals#chemical_test"
      get "/view_chemical_result" , :to=>"chemicals#view_chemical_result"
      get "/chemical_test_range", :to=>"chemicals#chemical_test_range"
      get "/service_item", :to=>"chemicals#service_item"
      post "/service_item_create" ,:to=>"chemicals#service_item_create"
      get "/service_item_display", :to=>"chemicals#service_item_display"

      post "/charge_create",:to=>"charges#charge_create"
      post "/update_coordinates",:to=>"trackings#update_coordinates"
      get "/show_points",:to=>"trackings#show_points"
      get "/deactive_points",:to=>"trackings#deactive_points"
      resources :clients do
        member do
          get "client_property" 
          post "update_client"
        end
      end
      resources :jobs do
        collection do
          get "today_schedule"
          get 'signature_job'
        end
        member do
          get "job_invoice"
          post "update_job"
          post "close_job"
          post "job_payment"
          post "reopen_job"
        end
      end
      resources :properties do
        member do
          post "update_property"
        end
      end
      resources :items do
        member do
          post "update_item"
        end
      end
      resources :quotes do
        member do
          post "update_quote"
          get "find_quote"
          post "signature_quote"
          post "quotes_image"
          post "quote_image_save"
        end
      end
      resources :invoices do
        member do
        post "update_invoice" 
        end
      end
      resources :basic_tasks do 
        collection do
          get "today_task"
        end
        member do
          post "update_task"
        end

      end

      resources :timesheets do
        member do
        post "update_timesheet" 
        end
      end

      resources :home do
        collection do
          get "weather"
        end
      end

      resources :expenses do 
        member do   
         post "update_expense"  
        end
      end
    end
  end

  resources :numbers do
    collection do
      post :update_ivr_number
      post :search
    end
  end
  resources :key_actions

  resources :keys

  resources :ivrs do

    collection do
      post 'create_beta'
      post 'add_sub_menu'
      post 'create_feedback'
      post 'check_email'
      post 'key_description'
    end
    member do
      get 'twiml/repeat_menu(/:sub_menu_id)', :to => "ivrs#twiml_repeat_menu" , :as => :twiml_repeat
      get 'twiml(/:sub_menu_id)' , :to => "ivrs#twiml" , :as => :twiml
      get 'handle_recording'
      get 'calls'
      get 'release'
      get 'templates'
      get 'apply_template'
      post 'sms_callback'
      get 'analytics'
      post 'filters'
    end
  end

  get "action_types" => 'action_types#index'

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash

    end
    collection do
      get :notify
      get :update_notify
      get :display_notify
    end

  end
  resources :classifieds do
    member do
      get :media
      patch :media_save
      post :media_save
    end 
  end

  resources :subscriptions do 
    collection do
      get :plan
      post :change_plan
      post :downgrade_plan
    end
  end
  resources :maps do
    collection do
      get :zoom
      get :optimize 
      get :assigned_team
      get :change_assign
      post :reassign
      get :map_show
      post :property_estimate
      get :lead
      get :add_marker
      post :display_address
      get :create_lead
      post :add_lead
    end
  end 
  resources :quotes
  resources :notifications 

  resources :events do
    collection do
      get :to_dos
      post :move
      post "visit_complete_event/:visit_id" => "events#visit_complete_event", as: "visit_complete_event" 
      get "visit_view_detail_event/:visit_id" => "events#visit_view_detail_event", as: "visit_view_detail_event"
      get "edit_visit_event/:visit_id" => "events#edit_visit_event", as: "edit_visit_event"
      post "update_visit_event/:visit_id" =>  "events#update_visit_event", as: "update_visit_event"
      get "destroy_visit_event/:job_id/:visit_id" =>  "events#destroy_visit_event", as: "destroy_visit_event"
      get 'new_job_event' => 'events#new_job_event', as: 'new_job_event'
      post 'search_job_client' => 'events#search_job_client', as: 'search_job_client'
    end
    get :view_detail
  end

  resources :basic_tasks do
    collection do
      get :to_dos 
      post :move
    end
    post :complete_basic_task
    get :view_detail
  end

  resources :jobs do 
    collection do 
      get "recurring_job"
    end
  end
  resources :properties do
    member do
      get :manually_geocode
      post "update_property"
    end
    collection do
      post :location_update
      post :property_service_plan
      post :pool_update_active
      get :convert_client
      post :converted
      get :lead_message
      post :lead_message_pdf
      post :property_tag
      post :tag_delete
      post :templates_display
      get :email_message
      post :message_email_sent
      get :lead_mailer
    end
  end

  resources :spa_pooles do 
    collection do
      get :property_pool_data
      post :pool_data_create
      post :pool_data_update
      get :pool_data_edit
      get :spa_data
      post :spa_data_create
      get :spa_data_edit
      post :spa_data_update
      post :calculate_gallonage
      post :calculate_spa_volume
      post :pool_shape_change
      post :spa_shape_change
    end
  end

  get "/dashboard" =>"dashboards#dashboard"
  get "/get_summary_data" =>"dashboards#get_summary_data"
  get "/get_quick_links"  =>"dashboards#get_quick_links"
  get "/weather_data"  =>"dashboards#weather_data"

  resources :clients do
    collection do
      get :demo_deactive 
      get :new_client
    end
    member do
      post :payment
    end
  end

  resources :documents do
    collection do
      get :document_box
      get :document_setting
      post :document_check
    end
    member do
      get :download
      get :delete_account # admin delete its account
    end
  end

  resources :intuits do
    collection do
      get :authenticate
      get :oauth_callback
      get :closed_qb_account
    end
  end

  resources :email_notifications do
    collection do
      get 'reply_message' 
      post 'message_create' 
      get 'thanks_message'
      post 'email_read'
      get 'chat_popup'
    end
  end

  resources :timesheets do 
    collection do
      get 'prev_day'
      get 'next_day'
      get 'category_new'
      get 'payroll'
      get 'prev_payroll'
      get 'next_payroll'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end
  end
  resources :expenses do
    collection do
      get 'mile_category' , :as => "expenses/mileage"
      post 'create_mileage'
      post 'category_create'
      post 'category_update'
    end
    member do
      get 'category_edit'
      get 'category_delete'
    end

  end
  resources :pool_services do 
    collection do 
      get "pool_service"
      get "spa_service"
      post "service_create"
      get "chemical_items"
      post "chemical_items_create" 
      get "pool_chemical_test"
      post "check_pool_test"
      get "chemical_used"
      post "chemical_used_create"
      get "service_items"
      post "service_items_create"
      get "market_source"
      post "source_create"
      post "source_update"
      get "service_plan"
      post "service_plan_create"
      post "service_plan_update"
      get :service_plan_label
      post :update_plan_label
    end
    member do
      get "source_edit"
      get "source_delete"
      get "service_plan_edit"
      get "service_plan_delete"
    end
  end
  resources :chamicals
  resources :postcards, only: [:index, :create] 
  devise_for :users, :controllers => {:sessions=>"sessions",:confirmations=>"confirmations",:registrations => "registrations",:passwords=>"passwords",:omniauth_callbacks => "omniauth_callbacks"}
  

  post '/twilio_call' =>"communications#twilio_call"
  post '/twilio_connect' =>"communications#twilio_connect"
  post '/property_note' =>"communications#property_note"
  post '/property_email' =>"communications#property_email"
  post '/property_sms'   =>"communications#property_sms"
  get '/more_activity'   =>"communications#more_activity"
  get '/edit_note_activity' =>"communications#edit_note_activity"
  post '/update_note_activty' =>"communications#update_note_activty"
  get '/filter_activity' =>"communications#filter_activity"

app/models/charge.rb
class Charge < ActiveRecord::Base

	BASE_CHARGE = 39
end

app/controllers/api/v1/charges_controller.rb
class Api::V1::ChargesController < Api::V1::ApiController
	skip_before_filter  :verify_authenticity_token

	def charge_create
		if !current_user.blank?
			if (params[:stripeToken].present? && params[:email].present? && params[:amount].present?)

				customer = Stripe::Customer.create(
		      :email => params[:email],
		      :card  => params[:stripeToken]
		    )

		    charge = Stripe::Charge.create(
		      :customer    => customer.id ,
		      :amount      => (params[:amount].to_f*100).to_i,
		      :description => 'payment-api transaction',
		      :currency    => 'usd'
		    )  rescue ""

		    if !charge.blank?
		    	render  :json=>{:status => "Payment successfully done!" }
	      else
				  render  :json=>{:status => "Something went Wrong, Please try again" }
			  end
			else
				render  :json=>{:status => "Please send email and amount" }
			end
		else
			render  :json=>{:status => "Failure Please login" }
		end
	end


	private
		def current_user
			User.find(params[:user_id]) rescue ""
		end
end

app/helpers/charges_helper.rb
module ChargesHelper

	def addons_total
		return 0
	end

	def get_add_on_status(user_add_on, add_on)
		unless current_user.add_on_statuses.where(add_on: add_on).first.blank?
			return true if current_user.add_on_statuses.where(add_on: add_on).first.status
		end
	end

	def discount_coupon(user,coupon)
		if user.plan_type=="solo"
			@amount="19.95"
		elsif user.plan_type=="team"
			@amount="29.95"
		elsif user.plan_type=="business"
			@amount="49.95"
		end
		return discount_amount=(@amount.to_f/coupon.percent_off)
	end

	def plan_type(user)
		if user.plan_type=="solo"
			amount="1995"
		elsif user.plan_type=="team"
			amount="2995"
		elsif user.plan_type=="business"
			amount="4995"
		end 
	end

	def find_total_payment(payment)
		refund_amount=payment.amount_refunded.to_f/100
		payment_amount = payment.amount.to_f/100
		return payment_amount - refund_amount
	end

	def plan_last_date(current_user)
		@charge=Charge.where(:user_id=> current_user.id).first
		return @charge.created_at.to_date+30
	end
end

app/views/charges/_coupon_form.html.erb
<div class="modal fade" id="coupon-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header new-modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
        <h4 class="modal-title" id="myModalLabel">Coupon</h4>
      </div>
      <div class="modal-body">
        <%if !@present_coupon.blank?%>

          You have already used this coupon and its expires date <%= @present_coupon.created_at.to_date + 30 %>
        <%end%></br>
          <i>Please Insert the Coupon Code Or ID</i> </br></br>
          <%= form_tag charges_coupan_create_path do%>
            <%= text_field_tag "coupan_id",nil,:placeholder=>"Please insert coupon id"%><br/>
            <div class="row text-right">
              <%= submit_tag "Save",:class=>" button_new_create pull-right save-new-btn1"%>
             <button type="button" class="model_cancel_button" data-dismiss="modal">CANCEL</button>
             
            </div>
          <%end%>
      </div>
    </div>
  </div>
</div>

app/views/charges/_information_form.html.erb
<div class="modal fade" id="information-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header new-modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
        <h4 class="modal-title" id="myModalLabel">Information</h4>
      </div>
      <div class="modal-body">

          <i>Please Insert the Information, Your Information is save with Us.</i> </br></br>
            <div class="row text-right">
             <button type="button" class="model_cancel_button" data-dismiss="modal">CANCEL</button>
            </div>
          
      </div>
    </div>
  </div>
</div>

app/views/charges/_plan_payment.html.erb
<div class="modal fade" id="payment_billing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header new-modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
        <h4 class="modal-title" id="myModalLabel">Billing</h4>
      </div>
      <div class="modal-body">

        <div id="account_details" class="fieldset billing_information">
          <div class="">
            <% if current_user.confirmed? %>
              <%= form_tag charges_create_path,:id=>"stripe-form" do%>
                <p>
                  <label for="billing_info_name">Name on Card</label>
                  <%= hidden_field_tag "base_charge", nil, value: @base_charge %>
                  <%= text_field_tag "charge[name]",nil,value: @charge.blank? ? "" : @charge.name,:id=>"billing_info_name"%>
                </p>
      
                <p>
                  <label for="billing_info_card_number">Card Number</label>
                  <%= text_field_tag "charge[card_number]",nil,:value=>@charge.blank? ? "" : @charge.card_number,:id=>"billing_info_card_number"%>
                  <img src="//d3ey4dbjkt2f6s.cloudfront.net/assets/app/icons/visa_48x29-78bbf7cfbc3ee34db0daf60b8b77a8dc.png" alt="Visa 48x29">
                  <img src="//d3ey4dbjkt2f6s.cloudfront.net/assets/app/icons/master_card_48x29-a6ebc0f3002c83d72e8f6e43d1a0c362.png" alt="Master card 48x29">
                </p>

                <p>
                  <label for="billing_info_exp_month">Expiry</label>
                 <%= select_tag("charge[exp_month]", options_for_select([["1","1"],["2","2"], ["3","3"], ["4","4"],["5","5"], ["6","6"], ["7","7"], ["8","8"],["9","9"],["10","10"],["11","11"],["12","12"]],:selected=>@charge.blank? ? "" : @charge.exp_month),:style=>"width: 50px;")%>
                 	<%= select_year(@charge.blank? ? Date.today : @charge.exp_year,  :start_year => Time.now.year, :end_year => Time.now.year + 15, :field_name => "exp_year", :prefix => :charge)  %>
                </p>
                <br>
                <p>
                  <label for="billing_info_ccv">CVC</label>
                  <%= text_field_tag "charge[cvc]",nil,:value=>@charge.blank? ? "" : @charge.cvc,:id=>"billing_info_ccv",:style=>"width: 50px;"%>
                </p>
                <br>
                <p>
                  <label for="billing_info_address1">Address 1</label>
                  <%= text_field_tag "charge[address1]",nil,:value=>@charge.blank? ? "" : @charge.address1,:id=>"billing_info_address1"%>
                  <br><span style="margin-left: 140px;" class="description">* as it appears on your credit card statement</span>
                </p>

                <p>
                  <label for="billing_info_address2">Address 2</label>
                  <%= text_field_tag "charge[address2]",nil,:value=>@charge.blank? ? "" : @charge.address2,:id=>"billing_info_address2"%> 
                </p>

                <p>
                  <label for="billing_info_city">City</label>
                  <%= text_field_tag "charge[city]",nil,:value=>@charge.blank? ? "" : @charge.city,:id=>"billing_info_city"%>
                </p>

                <p>
                  <label for="billing_info_state">State/Province</label>
                  <%= text_field_tag "charge[state]",nil,:value=>@charge.blank? ? "" : @charge.state,:id=>"billing_info_state"%>
                </p>

                <p>
                  <label for="billing_info_country">Country</label>
                  <%= country_select_tag "charge[country]", {priority: %w(US CA), prompt: 'Please select a country' ,:selected=>@charge.blank? ? "" : @charge.country},:class=>"billing_country" ,:style=>"width: 350px;"%>
                </p>

                <p>
                  <label for="billing_info_zip">Zip/Postal Code</label>
                  <%= text_field_tag "charge[zip_code]",nil,:value=>@charge.blank? ? "" : @charge.zip_code,:id=>"billing_info_zip"%>
                </p>
                <br>
                <p>
                  <label for="billing_info_email">Billing E-mail</label>
                  <%= text_field_tag "charge[email]",nil,:value=>current_user.email,:id=>"billing_info_email"%>
                  <span class="description">for your invoices</span>
                </p>

              <%end%>

             <div class="row text-right"> 
              <button type="button" class="model_cancel_button" data-dismiss="modal">CANCEL</button>
              <input type="submit" value="Submit" style="float:right" name="commit" class="update_button_setting save spin_on_click save-new-btn1" id="stripe_button_submit">
             </div>

            <% else %>
              <p class="flash flash_warning" style="width:auto !important;">
                You must verify your e-mail before you enter your credit card. If you did not receive a Welcome Email, <%= link_to 'click here', new_user_confirmation_path, style: "color:blue;" %>.
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charges/_receipt_view.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
        <h4 class="modal-title" id="myModalLabel">Payment Detail</h4>
      </div>
      <div class="modal-body">
 
        <h3 style="text-align:center; line-height: 20px;">Receipt</h3>
        <%= link_to  charges_receipt_pdf_path(@payment.id,:type=>@account_type) do %>
        <%=image_tag "pdf_view_receipt.png"%>
        <%end%>
        
        <div class="rec-box">
          <h3>$<%= @payment.amount.to_f/100 rescue ""%> &nbsp;</h3>
          <h4><%= @payment.card.brand rescue ""%> <%= @payment.card.last4 rescue ""%></h4>
          <div class="rec-box-date">
            <span style="float:left;"><%= Time.at(@payment.created).strftime("%B %d ,%Y") rescue ""%></span>
            <span style="float:right;"><% if @payment.receipt_number%>#<%= @payment.receipt_number%><%end%></span>
          </div>
        </div>

        <table class="table payment-display">
          <tr>
            <td style="width:80%"><b>Description</b></td>
            <td><b>Price</b></td>
          </tr>


          <tr>
            <td><%= @payment.description rescue ""%></td>
            <td>$ <%= @payment.amount.to_f/100 rescue ""%></td>
          </tr>

          <tr>
            <td>Refund Amount</td>
            <td>$ <%=@payment.amount_refunded.to_f/100 rescue 0%></td>
          </tr>

          <tr>
            <%if @payment.amount_refunded==0%>
              <td>Total</td>
              <td>$<%= @payment.amount.to_f/100 rescue ""%></td>
            <%else%>
              <td>  Adjusted total </td>
              <td>$<%= find_total_payment(@payment).round(2) rescue 0%></td>
            <%end%>  
          </tr>
          
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/charges/_total_charge.html.erb
<div class="container">
  <div id="cost_breakdown" class="clearfix" style="margin-top: 25px;">
    <div class="bar clearfix" style=" display: inline;">
      <div class="cost_type sum_for_total" >
        <h5>Base Cost<small>?</small></h5>
        <div>
          <sup class="amount_sign">$</sup><%= @base_charge.to_f/100 rescue 0 %>
        </div>
      </div>
      <div class="cost_type sum_for_total" >
        <h5>Additional Logins <small>?</small></h5>
        <div>
          <sup class="amount_sign">$</sup>0
        </div>
      </div>
      <div id="addons_summary" class="cost_type sum_for_total" >
        <h5>Add-ons<small>?</small></h5>
        <div>
          <sup class="amount_sign">$</sup><%= @active_addon %>
        </div>
      </div>
      <div class="cost_type" id="monthly_charge_amount" >
        <h5>Estimated Monthly Total <small>?</small></h5>
        <div>
          <sup class="amount_sign">$</sup><%= @base_charge.to_f/100 + @active_addon.to_i %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charges/add_on.js.erb
$("#add_on_display").html("<%= escape_javascript(render 'charges/add_on') %>");
$("#add_on_display").modal('show');

app/views/charges/new.html.erb
<div class="client_index">
  <div class="main_container">
    <%= render "clients/error_message_and_flash" %>
    <%#= render partial: "total_charge" %>
    <h4 class="title1-font">Billing Overview</h4>
    <div class="main_column">
      <div class="payment-display">
        <div class="row charge_view">
          <div class="span1">
            Plan
          </div>
          <div class="span8">
            <%if @charge.blank? %>
              <b>Small</b> Using 7 to 10 private Repositories.
            <%else%>
              Your current plan is <b><%= current_user.plan_type%></b> And you want to change their plan click on change plan button.
            <%end%>       
          </div>
          <div class="span3">
            
            <%= link_to("<i class='icon-gear'></i> Change Plan".html_safe,plan_subscriptions_path,:class=>"button pull-right")%>
          </div>
        </div>

        <div class="row charge_view">
          <div class="span1">
            Payment
          </div>
          <div class="span8">
            <%if @charge.blank? %>
              American Express 3*******4001 Expiration 4/2017<br/>
              Next Payment Due 2015-01-25<br/>
              Amount $12.00.
            <%else%>
              American Express XXXX-XXXX-XXXX-<%=@charge.card_number.last(4)%> Expiration <%= @charge.exp_month%>/<%= @charge.exp_year%><br/>
              Next Payment Due <%= @subscription.active_date+30%><br/>
              Amount $<%=  (@subscription.amount.to_f)/100%>.
            <%end%>
          </div>
          <div class="span3">
            <button type="button" class="button pull-right" data-toggle="modal" data-target="#payment_billing"><i class='icon-credit-card'></i> Update payment method
            </button>
          </div>
        </div>

        <div class="row charge_view">
          <div class="span1">
            Coupon
          </div>
          <div class="span8">
            <%if @present_coupon.blank?%>
              You don't have active coupon.
            <%else%>
              You have active coupon.</br>
              <%=@present_coupon.percent_off%> % off <%= @present_coupon.duration%>
            <%end%>
          </div>
          <div class="span3">
            <button type="button" class="button pull-right" data-toggle="modal" data-target="#coupon-form"><i class="icon-gift"></i> Redeem a coupan
            </button>
          </div>
        </div>

        <div class="row charge_view">
          <div class="span1">
            Extra Info
          </div>
          <div class="span8">
            You have not added any additional information of your receipts.
          </div>
          <div class="span3">
            <%#= link_to("<i class='icon-pencil'></i> Add Information".html_safe,"#",:class=>"button pull-right")%>
             <button type="button" class="button pull-right" data-toggle="modal" data-target="#information-form"><i class="icon-pencil"></i> Add Information
            </button>
          </div>
        </div>
      </div>  
    
      <div class="display_payment-view">
        <%if !@all_payment.blank?%>
          <table class="table">
            <tr>
              <th>ID</th>
              <th>DATE</th>
              <th>PLAN</th>
              <th>PAYMENT METHOD</th>
              <th>RECEIPT</th>
              <th>AMOUNT</th>
              <th>STATUS</th>
            </tr>
            <tbody>
              <%@all_payment.each_with_index do |payment,index|%>
                <tr>
                  <td><%=index+1%></td>
                  <td><%=Time.at(payment.created)%></td>
                  <td><%=@charges_plan[index]%></td>
                  <td><%=payment.card.brand%> <%=payment.card.last4%></td>
                  <td><%=link_to "view receipt",view_receipt_charge_path(:id=>payment.id,:data=> @charges_id[index]) ,:remote=>true,:data=>{toggle: "modal",:target=>"#view_receipt"}%></td>
                  <td>USD<%=payment.amount.to_f/100 rescue ""%></td>
                  <td><%=payment.paid ? "Succeeded" : "Pending"   rescue "" %></td>
                </tr>
              <%end%>  
            </tbody>
          </table>
        <%else%>
          <i style="text-align:center;">NO PAYMENT YET</i>
        <%end%>  
      </div>
    </div>  
    <div class="modal fade" id="payment_receipt" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 
    </div>
    <%= render "charges/coupon_form"%>
    <%= render "charges/plan_payment"%>
    <%= render "charges/information_form"%>
  </div>
</div>

<script>
stripeTokenGenerateTest()
</script>

app/views/charges/payment_terminal.js.erb
$("#payment_terminal").html("<%= escape_javascript(render 'charges/payment_terminal') %>");
$("#payment_terminal").modal("show");

app/views/charges/view_receipt.js.erb
$("#payment_receipt").html("<%= escape_javascript(render 'charges/receipt_view') %>");
$("#payment_receipt").modal("show");